lesson2
Alesia-M/webix-start pull request #2
Opened 2022-04-06 15:43 UTC by Alesia-M

2022-04-06 16:32 UTC, VeraOrekhXB requested changes

2022-04-06 16:32 UTC, VeraOrekhXB commented on app.js
> +webix.ui({
На мой взгляд лучше создать попап до создания кнопки. @HelgaListopad, влияет ли как-то порядок в этом случае?
Кстати, в конфиге кнопки в свойстве popup не обязательно всегда писать id попапа, можно там сразу же добавить конфиг попапа (в документации сказано, что значение может быть только строкой https://docs.webix.com/api__ui.button_popup_config.html)

2022-04-06 16:32 UTC, VeraOrekhXB commented on app.js
> +		template: "#name#",
В твоём случае необязательно нужно добавлять темплейт, обычно он используется тогда, когда данные подгружаются с сервера. Без темплейта текст по дефолту берётся из свойства ```value```

2022-04-06 16:32 UTC, VeraOrekhXB commented on app.js
> +							invalidMessage: "Enter year between 1997 and 2022"
Если поле может принимать только числовые значения, то есть смысл ограничить ввод других символов
И вот, например, случай, когда твои проверки могут не сработать(см. Rating)
![image](https://user-images.githubusercontent.com/91135127/162021381-ff74d0d4-8c7d-454f-b6a3-6518c5385ae9.png)
Также должно работать экранирование
![image](https://user-images.githubusercontent.com/91135127/162021697-10c5ace3-3865-4870-ad5d-27ed90c48c62.png)

2022-04-06 16:32 UTC, VeraOrekhXB commented on app.js
> +											$$("dataList").add(item);
После добавления новой строки форма должна быть очищена

2022-04-06 16:32 UTC, VeraOrekhXB commented on app.js
> +});
Т.к. количество кода постепенно увеличивается, будет лучше разделить код хотя бы на отдельные функции

2022-04-06 16:32 UTC, VeraOrekhXB commented on app.js
> +	position: 'right',
У попапа в свойстве position могут быть только следующие значения: 'center' и 'top'
https://docs.webix.com/api__link__ui.popup_position_config.html

2022-04-06 16:32 UTC, VeraOrekhXB commented on app.js
> +						id: "profile_btn",
Старайся придерживаться одного стиля написания id: или camel case, или через _

2022-04-06 18:09 UTC, Alesia-M commented on app.js
> +											let item = $$("dataForm").getValues();
не понимаю, как вынести ее из общего списка, если форма там привязана к основному расположению на странице :( С попапом проще вышло, он привязан просто к кнопке о_О"

2022-04-06 18:10 UTC, Alesia-M commented on app.js
> +											let item = $$("dataForm").getValues();
done

2022-04-06 18:10 UTC, Alesia-M commented on app.js
> +								webix.message({ text: key + " field is incorrect", type: "error" });
а разве они не заданы где-то в программе автоматом выдавать с маленькой значение, если идет общий код, а не каждое сообщение прописано отдельно? Впрочем, по заданию там было достаточно просто invalidMessage выводить, так что убрала попапы об ошибках .D

2022-04-06 18:10 UTC, Alesia-M commented on app.js
> +webix.ui({
не очень поняла, о чем речь даже с документацией :(

2022-04-06 18:10 UTC, Alesia-M commented on app.js
> +		template: "#name#",
done

2022-04-06 18:11 UTC, Alesia-M commented on app.js
> +							invalidMessage: "Enter year between 1997 and 2022"
проверку на числа сделала, но не понимаю, что не так с экранированием оО" вроде работает и выделяет при добавлении. или наоборот не должно так быть? и должен возвращаться с тегами?

2022-04-06 18:11 UTC, Alesia-M commented on app.js
> +											$$("dataList").add(item);
done

2022-04-06 18:11 UTC, Alesia-M commented on app.js
> +	position: 'right',
убрала

2022-04-06 18:11 UTC, Alesia-M commented on app.js
> +						id: "profile_btn",
done

2022-04-06 23:34 UTC, HelgaListopad commented on app.js
> +webix.ui({
На самом деле не влияет (непосредственно вызов по id случается в момент клика).
Но я согласна (и всем пишу это в ревью), что логически было бы правильнее поменять местами вызовы:
```js
webix.ui( popupConfig );  // тут popup с id: "popup_menu"
webix.ui( mainUI );       // тут любая логика, которая его задействует ( { view:"button", popup: "popup_menu"} )
```
Собственно, это сейчас и нужно сделать.

@VeraOrekhXB а про документацию - да, косяк, поправим. 
В лекции пример с объектом я не давала (и здесь так сейчас делать не нужно), но сработает: 
https://snippet.webix.com/yvz0r0l5

2022-04-07 00:15 UTC, HelgaListopad commented on app.js
> +							invalidMessage: "Enter year between 1997 and 2022"
В [задании](https://docs.google.com/document/d/1pOb4KrHb84AqhxVXnwRXvQNtfqbG-tY3x0iHTVHVo9M/edit?usp=sharing) действительно не было требований к безопасности и сохранению внешнего вида вносимых данных для такого случая. На втором занятии для этого имхо рано :)
Но тема полезная. Поэтому включусь в обсуждение и дам пример того, что на мой взгляд сейчас стоит сделать, раз об этом зашла речь (см. пункт **1.2**). 
Если есть несложные альтернативы, то финальный вариант на усмотрение @VeraOrekhXB

По умолчанию таблица отрисовывает данные так, как они пришли. 
Если в данных есть теги, то они будут включены в отрисовку как обычный HTML (на скриншоте выше это видно).
С точки зрения безопасности, если из формы таким образом передать любой HTML код (а туда можно вписать и обработчики событий, и вызов скрипта), то это очень плохо.
Поэтому есть несколько вариантов:

1. перед тем, как вызывать `table.add(values)`
  1.1. либо вырезать теги через регулярное выражение
  1.2. либо использовать [webix.template.escape](https://docs.webix.com/api___template_escape.html) для их преобразования в безобидные [HTML Entity](https://developer.mozilla.org/en-US/docs/Glossary/Entity): https://snippet.webix.com/6yl7aha1
2. после `table.add(values)` применить один из методов выше, но уже через события таблицы (не было на занятиях, поэтому не стоит сейчас разбирать)

2022-04-07 07:11 UTC, VeraOrekhXB commented on app.js
> +						id: "profile_btn",
Это касалось всех id в файле: здесь у тебя через нижнее подчёркивание, ниже у таблицы и у формы camelCase

2022-04-07 07:11 UTC, VeraOrekhXB commented on app.js
> +							invalidMessage: "Enter year between 1997 and 2022"
Согласна, лучше сейчас просто использовать [webix.template.escape](https://docs.webix.com/api___template_escape.html). Ещё один из возможных вариантов - это использование регулярных выражений.

2022-04-07 07:11 UTC, VeraOrekhXB commented on app.js
> +											let item = $$("dataForm").getValues();
Я имела в виду, что нежелательно каждый раз вызывать ```$$("dataForm")```. Если один раз встречается в функции, тогда так можешь сделать, если нет, создай переменную, например: ```const form  = $$("dataForm")```.

2022-04-07 07:13 UTC, VeraOrekhXB commented on app.js
> +								webix.message({ text: key + " field is incorrect", type: "error" });
В задании об этом ничего не сказано, просто так было бы более user friendly что ли

2022-04-07 08:59 UTC, Alesia-M commented on app.js
> +											let item = $$("dataForm").getValues();
ааа... я просто подумала, что надо вынести весь блок формы, у которого эта айдишка х")
done

2022-04-07 08:59 UTC, Alesia-M commented on app.js
> +webix.ui({
done

2022-04-07 09:00 UTC, Alesia-M commented on app.js
> +							invalidMessage: "Enter year between 1997 and 2022"
сделано :)

2022-04-07 09:00 UTC, Alesia-M commented on app.js
> +						id: "profile_btn",
я забыла, что они еще где-то остались неисправленные, упс :")

2022-04-07 09:55 UTC, VeraOrekhXB approved these changes

2022-04-07 10:00 UTC, HelgaListopad approved these changes

2022-04-07 10:01 UTC, merged