Lesson5
Alesia-M/webix-start pull request #5
Opened 2022-04-11 17:35 UTC by Alesia-M

2022-04-11 19:06 UTC, VeraOrekhXB requested changes

2022-04-11 19:06 UTC, VeraOrekhXB commented on app.js
> +			editor: "text",
Было бы неплохо добавить проверку при редактировании значения, чтобы оно было непустое

2022-04-11 19:24 UTC, Alesia-M commented on app.js
> +		if (form.isDirty()) {
они были 2 в 1, но тогда на пустой форме не срабатывала валидация, поэтому мы разбили ее на две части .)

2022-04-11 19:30 UTC, Alesia-M commented on app.js
> +	$$("categoryId").sync(catCollection)
я ее видела, но при этом оно вроде как и все равно работает, пока так и не поняла почему

2022-04-12 06:10 UTC, VeraOrekhXB commented on app.js
> +		if (form.isDirty()) {
Должно cработать, если поставить form.validate на первое место ```if (form.validate() && form.isDirty())```

2022-04-12 06:17 UTC, VeraOrekhXB requested changes

2022-04-12 06:17 UTC, VeraOrekhXB commented on app.js
> +				const newValue = $$('catValue').getValue()
Перед добавлением стоит добавить проверку на непустое значение

2022-04-12 09:41 UTC, Alesia-M commented on app.js
> +	$$("categoryId").sync(catCollection)
я ее уже убрала, не просто прописала изначально

2022-04-12 09:59 UTC, VeraOrekhXB requested changes

2022-04-12 09:59 UTC, VeraOrekhXB commented on app.js
> +			id: "categoryId", options: catCollection,
При добавлении нового фильма выставляется другая категория из-за того, что в $init categoryId всегда генерируется. Сделай так, чтобы значение генерировалось только тогда, когда нет значения

2022-04-12 10:15 UTC, VeraOrekhXB approved these changes

2022-04-12 12:52 UTC, HelgaListopad requested changes

2022-04-12 12:52 UTC, HelgaListopad commented on app.js
> +				if (newValue !== '' && newValue !== 'New category') {
А почему нельзя "New category" ?
Если ты хотела отобразить в компоненте text подсказку, используй там `placeholder` и удали эту часть проверки (`newValue !== 'New category'`)

2022-04-12 12:52 UTC, HelgaListopad commented on app.js
> +				return false;
Такой код оставит эдитор открытым, но никак не помешает открыть ещё один - так можно получить мноожество открытых.
Нужна дополнительная проверка, запрещающая открывать новый эдитор, если активен старый ( `onBeforeEditStart` ), вроде такой: https://snippet.webix.com/nmekx3xs

2022-04-12 12:52 UTC, HelgaListopad commented on app.js
> +		value: 1,
Начальное value можно не выставлять

2022-04-12 12:52 UTC, HelgaListopad commented on app.js
> +		yCount: "3",
Не поддерживается компонентом и не должно быть задано строкой.
Если идея в том, чтобы выставить высоту выпадающему списку, то можно так
https://snippet.webix.com/xuesm7iy

https://docs.webix.com/desktop__advanced_combo.html

2022-04-12 18:09 UTC, merged